### Import Dependencies

In [1]:
import openai
import pandas as pd
import tiktoken

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import FieldCondition, MatchAny, Filter
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### Create Qdrant Collection for hybrid Search

In [2]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [3]:
qdrant_client.create_collection(
    collection_name="Amazon-reviews-collection-01",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    }
)

True

In [4]:
qdrant_client.create_payload_index(
    collection_name="Amazon-reviews-collection-01",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [5]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [6]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Read the sampled dataset with Amazon Reviews Data

In [9]:
df_reviews = pd.read_json("../../data/Electornics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [10]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True

In [11]:
len(df_reviews)

122840

### Preprocess tile and features

In [12]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [26]:
# def count_tokens(text):
    
#     encoding = tiktoken.encoding_for_model("text-embedding-3-small")
    
#     return len(encoding.encode(text))

def count_tokens(row):

    encoding = tiktoken.encoding_for_model("text-embedding-3-small")

    return len(encoding.encode(row["preprocessed_data"]))

In [25]:
count_tokens("How are you doing today?")

6

In [27]:
df_reviews["preprocessed_data"] = df_reviews.apply(preprocess_reviews_data, axis = 1)
df_reviews["token_count"] = df_reviews.apply(count_tokens, axis = 1)

In [28]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,token_count
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True,Nixplay 10.1 touch screen digital picture fram...,255
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True,"Great so far... Speedy delivery, great sound a...",27
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True,Set up is not that easy. Nice looking set but ...,18
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True,Waste of money Very unhappy with this keyboard...,66
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True,Nice Work great,3

In [29]:
len(df_reviews)

122840

In [ ]:
# Filter out token counts less 8192: when using open ai's free embedding model
df_reviews = df_reviews[df_reviews["token_count"] < 8192]

In [31]:
len(df_reviews)

122840

In [32]:
total_tokens = df_reviews["token_count"].sum()

In [33]:
total_tokens

np.int64(6506026)

### Embed the text and add additonal fields to the payload of each vector for reviews

In [35]:
df_data_to_embed = df_reviews[["preprocessed_data", "parent_asin"]]

In [36]:
df_data_to_embed.head()

                                   preprocessed_data parent_asin
0  Nixplay 10.1 touch screen digital picture fram...  B0BNXXNBB4
1  Great so far... Speedy delivery, great sound a...  B0C72D4J46
2  Set up is not that easy. Nice looking set but ...  B09XGQQ98K
3  Waste of money Very unhappy with this keyboard...  B07L5L22ZL
4                                    Nice Work great  B09LTX3SQX

In [37]:
data_to_embed_reviews = df_data_to_embed.to_dict(orient="records")

In [39]:
data_to_embed_reviews

[{'preprocessed_data': "Nixplay 10.1 touch screen digital picture frame I purchased this digital frame on a treasure truck deal - it  works.  You will have to load the app and follow directions to bluetooth transfer pics you choose from your gallery to the frame.  I purchased an additional memory chip - but it turns out there is no place to install the chip so don't waste your time there.  You can set a regular time to 'run' the frame or manually turn it off and/or on.  You can 'shuffle' OR play all your uploaded pics.  You do not get to choose the 'fade' that happens between pics, but you do get to choose how long each pic stays on the frame before moving to the next pic. Picture quality is pretty good - about as good as the pics you download on to it.  It's close to an 8x10 frame.  Not sure why they call it a 'touch screen' cause I can't figure out what you can do by touching the screen - but ok. It comes with charging cord, regular plug in - there appears to be a mini USB port, but I haven't tried it.  Having said all this I never hesitate to update my reviews should new info seem useful.",
  'parent_asin': 'B0BNXXNBB4'},
 {'preprocessed_data': "Great so far... Speedy delivery, great sound and a great warranty... Let's see how it lasts will update if anything changes.",
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Set up is not that easy. Nice looking set but installation instructions are not well made.',
  'parent_asin': 'B09XGQQ98K'},
 {'preprocessed_data': "Waste of money Very unhappy with this keyboard, it would slip and slide all over my keyboard tray., and  I had to look carefully to locate some keys that had been moved around a bit.  The mouse, however, was awesome, so for that reason I'm keeping the product and will use only for emergencies. .",
  'parent_asin': 'B07L5L22ZL'},
 {'preprocessed_data': 'Nice Work great', 'parent_asin': 'B09LTX3SQX'},
 {'preprocessed_data': "Works I don't like the look, but it does the job.<br />**********update************<br />After using this a while I decided to buy one of these for my mom. The one she had was a real pain in the wherever!<br />We're both pleased with the swivel capability....it's something I'd always complained about on my old one that didn't swivel, which made a cramped area or not being able to use an outlet because the plug-end of cord was oversized.<br />I've also changed my 4 star to a five...",
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': 'Great tv mount I used this to mount a 65” fire tv. Took me about an hour from start to finish. Instructions are fine and if your generally a handy person it shouldn’t be a difficult job. I did get some help when I put the TV on, so not a full one person job. Work well and is very adjustable. Overall very pleased.',
  'parent_asin': 'B09N922QG2'},
 {'preprocessed_data': 'Great AirTag holder Works great and is very durable. Protects the AirTag well and easily clips on to backpack or can be added to keychain. It’s also nice looking.',
  'parent_asin': 'B0B9L1N68J'},
 {'preprocessed_data': 'Decent I could not get the holder that holds the monitor to stay up. It kept sliding down. Others reviewed it well, so worth trying, just not for me.',
  'parent_asin': 'B0C6FJFRJG'},
 {'preprocessed_data': 'Worst cord ever Worst cord ever. The first one I bought wouldn’t plug in correctly and I could only hear sound on one side. They replaced it and here we are, only 2 months later and it’s already not working. Don’t even waste your $10.',
  'parent_asin': 'B0CC4HBS85'},
 {'preprocessed_data': 'Four Bays Are Convenient When Searching Drives From Retired PCs I have a collection of old SATA drives from retired (and now recycled) desktop PCs.  I use this SABRENT USB 3.0 FOUR-BAY 2.5” HARD DRIVE DOCKING STATION WITH FAN (DS-4SSD) to see into the 2.5” (slender) drives, and to occasionally copy off a file that wasn’t transferred when I set up the replacement PCs.  It’s convenient to have the four bays available when I’m not sure which drive contains the file I’m seeking.  I can set up four drives at once to speed the process.<br /><br />In my experience, Sabrent products always perform well, and they’re always reasonably priced.  They deliver good value for the money.',
  'parent_asin': 'B0BVH2C84P'},
 {'preprocessed_data': 'Two USB drives failed to work. First item failed to work  a replacement was sent and it failed to also work.',
  'parent_asin': 'B0887X4XSD'},
 {'preprocessed_data': '🙂 🙂', 'parent_asin': 'B09VBWBHBC'},
 {'preprocessed_data': 'greta for eery day use and the bass was solid. for the price point it is great as I can use it for my spin classes, walking around [ there is no noise cancellation, which is perfecter jungle living as you need to be aware of the surroundings], and so easy to set up.  I was able to login into multiple devices, but you need to reconnect if you do that, otherwise it will connect to the last device it was bluetooth connected to.<br /><br />I accidentally dropped this into cup of cold water and it still worked as the seals are pretty tight.  battery charge was excellent as long as you remember to with it off after use.  charge time as fast and thank goodness it uses the modern C connection design.  love it.',
  'parent_asin': 'B0B3ZKBJ8V'},
 {'preprocessed_data': 'Great Looking and Functioning Cable I am super happy with this cable, mostly because it looks great!  I have to admit we do not push the speed capabilities with any of our equipment, but it works perfectly well between a PS4 and our big TV.  The cable hangs much better from the back of the TV and just plain looks good.  I wish I could match all our cable to this wonderfully neutral, braided gray.  Absolutely perfect!',
  'parent_asin': 'B08HCDV6TT'},
 {'preprocessed_data': "Beefy but bombastic. What a superb charger! I used this to replace my Amazon-brand brick, which, while it was great, needed to retire (I could hear rattling inside). This is about 1/3 larger than my previous charger, but still fits in my electronics organizer. The cable it comes with is also fantastic; it's the perfect length to keep my computer charged from the wall, and it's braided--yay for braids!<br /><br />There are two USB-C ports with different charging power. The weaker one won't charge if it's not powerful enough, which I realized when trying to charge my MacBook. That's pretty cool because I can charge two items at once, one with a bigger battery and one with a smaller. There's also a USB-A port that can be used at the same time. I notice a dip in charging power when all three ports are used, but that's kind of assumed considering it's used to charge three items at once.",
  'parent_asin': 'B0B129DM9T'},
 {'preprocessed_data': "As a backpack organizer, it fits my needs (currently). I don't use this as a laptop sleeve. Instead, I got this because I thought I could use it as a backpack organizer. I carry various notebooks, writing, and drawing supplies with me. I'm not an artist by any means, but I like to journal using different media. Having them loose in my backpack didn't make it easy to find things or have everything in one organized location. This sleeve drastically reduced clutter and makes it faster and easier for me to journal.<br /><br />Currently, it holds my journal, a soft writing mat, my Sonnenleder pencil case, a few fountain pens, a whiteboard notebook, and some markers (dry-erase, Sakura, permanent). It's a tight squeeze, with the front pocket, but overall I have no worries of anything being damaged. In fact, I feel everything is more secure in this. I also love that there are pockets to tuck the handles; I use one only just to pull the sleeve out of my backpack.<br /><br />The front pocket sometimes gets caught in my backpack when I take it out. There's a bit of fabric on the cover of the front pocket so as to conceal the zipper; I wish there wasn't as much excess fabric, or at least some way to stick it closer to the sleeve (like some Velcro or something).<br /><br />But now, instead of looking for and taking out a bunch of things from my backpack, I just pull this out and everything is one, easy-to-locate space.",
  'parent_asin': 'B09XGTMY6X'},
 {'preprocessed_data': 'not too curved perfect size perfect curve i love it very crisp',
  'parent_asin': 'B0BDWN4RHW'},
 {'preprocessed_data': 'sturdy great and sturdy and can handle a ton of weight and a couple moves!',
  'parent_asin': 'B0C6FJFRJG'},
 {'preprocessed_data': "Superb value! Awesome color, really stands out when your looking for the cord plus the length is good. So far no issues while charging.<br />I'm happy 😊",
  'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': 'Multiple outlets Easy to install, just plug in and screw it in. Plus the outlets move to make room for larger cords.',
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': "Should have found this sooner Streamlined way to ad additional outlets versus other products.  Works fine & plugs go in & pull out easily, but don't get knocked out.",
  'parent_asin': 'B0BB6TYK7V'},
 {'preprocessed_data': 'Earbuds Great product', 'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': '4 🌟 Nice for the price', 'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': "Great on Laptop's I work at home. And it was getting harder and harder to hear the people in the officer. So far, its been working really well. I even had to turn down the volume. I think this great. And the price was great too!",
  'parent_asin': 'B09QCC1SP1'},
 {'preprocessed_data': 'Worth the money spent !! I just recieved the item, and have proceeded touge them the sound quality is excellent.',
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Will buy again. The ear hook is not adjustable to individual ear sizes. I used the earbuds for everyday functions due to ambulating with crutches daily.',
  'parent_asin': 'B0C2Q17PND'},
 {'preprocessed_data': "Listing specifically what it dose Beed 1 in 2 out. Description didn't say it was 2 in 1 out",
  'parent_asin': 'B09YH2K3FL'},
 {'preprocessed_data': 'Great pallet Perfect for water colors!',
  'parent_asin': 'B0C6FB3WGW'},
 {'preprocessed_data': 'Portable, Quality Means for Listening to Music I like listening to music when I spend time in my backyard. I used to rely on my alexa for this purpose, but more often than not, the volume and clarity were not that good. A portable Bluetooth speaker was the answer and I found just what I needed with this Bluetooth, from Tpone.<br /><br />What you get with this Bluetooth is a portable, chargeable speaker with that offers up to 18 hours of playback on a single charge. Getting it fully charged will take time, but after that, it’s a matter of pairing it with the Bluetooth on your phone. In about two minutes, it will be ready for use.<br /><br />The sound quality you get with this Bluetooth speaker is quite good. I like the bass, and for my needs, the volume is sufficient. It’s not powerful enough to blast you away, but for what I need, the volume level works. I use it mostly when I sit on my back patio and/or jump in the pool. I don’t need extreme volume, so this works. There is a plus and minus button on the unit that at first seem like volume controls, but they are not. If you push these, the music will either advance forward or backward to the next song on the list. The volume is controlled by your phone or whatever device you have paired.<br /><br />There are different colored lights on this speaker that react to the music, adding to the visuals. Again, for my needs, I really don’t care about the lights. But I can see how this could certainly add to the coolness factor for some people. The added colors and the way they react to the intensity of the music is a nice addition. Oh, and I like that I can use this to charge my phone. If a phone is paired, it could drain the phone’s power quickly while you play music. You can easily counter this by plugging your phone directly into the unit, helping to keep your phone charged.<br /><br />Having the means to listen to music is an ongoing need for me. Whether I am listening to music in my backyard or taking a trip to a nearby beach, I need to be able to play my tunes and the easiest way is to use a portable Bluetooth speaker. This Bluetooth from Tpone delivers on most all counts. The easy pairing, the bass, and the overall sound quality make this an easy winner and an excellent Bluetooth choice.',
  'parent_asin': 'B0B6HSDGML'},
 {'preprocessed_data': "Good cables! I needed good cables to run my phone to my new car, it made a huge difference when I hooked up these cables. I'm not a techy. Just saying it mattered a lot!",
  'parent_asin': 'B0B6J78QZP'},
 {'preprocessed_data': "No data connection for Pixel 6 Just received today.  Neither of the two let's me connect to transfer data.  I can't say if it works for charging, but I bought for both data and charging, so it's a no go for me.",
  'parent_asin': 'B0B4DCFYF9'},
 {'preprocessed_data': 'Cruise Worthy Worked great, cruise personnel didnt balk about it as it is wall based and does not have any wires for extending',
  'parent_asin': 'B09PZMVHQB'},
 {'preprocessed_data': 'Fits nice wish they  glowed in the dark like they said Very nice fit to my controllers only wish they actually glowed in the dark like they said they did, but they do the job they where meant to do.',
  'parent_asin': 'B0BW5KSV6Z'},
 {'preprocessed_data': "Does the Job I like the Amazon brand cloth covers. They have a nice grippy texture are easy to clean and fit the device well. The magnetic wake on opening feature works well. I do wish there was a better variety of colors maybe designs or patterns but that's just not super important.",
  'parent_asin': 'B09FRWJ2NJ'},
 {'preprocessed_data': 'Great fill lights I used AI bought these for fill lights.  They can provide the equivalent of a 20 W incandescent light, which is plenty of light with modern DSLRs.  One or two can fill int he shadows when shooting in low light or backlit situations.  battery life is excellent with no problems getting over 90 minutes of life at full power and much longer with even a small decrease in output.  If I had any ideas for improvement, it would be to have presets for common light sources (daylight, tungsten, etc.) to better match the primary light source.  The value of the unit is great, and I highly recommend it.',
  'parent_asin': 'B0BZTW4NH1'},
 {'preprocessed_data': 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
  'parent_asin': 'B0B6ZZH83Y'},
 {'preprocessed_data': 'Works great Amazing cable for playing games',
  'parent_asin': 'B0BMDNNH23'},
 {'preprocessed_data': 'Better than I thought I am really enjoying the sound quality from these as I needed to switch from a corded headset to something wireless. This is Bluetooth but the Bluetooth chip works well and doesn’t seem to have issue where it disconnects from my laptop and connects to my phone (I’ve had this with a few speakers).<br /><br />The mic works great as I do user testing and the sound quality is important for good feedback as a tester.<br /><br />I was pleasantly surprised to find out that the chip isn’t needed unless Bluetooth isn’t available on the device. There was no issue with connectivity either as my laptop recognizes the USB Bluetooth chip and automatically paired with the headset. A plus for me since my laptop tends to lag.<br /><br />The headset has a good/decent look to it. The earpieces are squishy and comfortable. The headset adjusts easily. The plastic seems to be of decent quality so putting them on and taking off repeatedly should not be an issue. Very pleased overall.',
  'parent_asin': 'B0BWM11RM6'},
 {'preprocessed_data': 'No me gusto mucho No me gusta porque no puedo conectarla a la laptop para usarla  como web cam y grabar',
  'parent_asin': 'B0BQ79PC5Q'},
 {'preprocessed_data': 'Great little fan Perfect for work, can use with usb or block (not included)',
  'parent_asin': 'B0BGR6R1SR'},
 {'preprocessed_data': "Next to useless After a week, I am giving up on this sound bar and going back to my tv speakers. It worked well for 24 hours and then began to have glitches.<br /><br />The optic connection is ok, but the included cable is loose and doesn't want to stay out. The outlet plug is huge and the cord is short - there's no reason for that.<br /><br />Mostly though, the remote and overall functionality is driving me nuts. The power buttons on the remote do not work at all. I have to manually turn on the sound bar with a button on the side. If I pause a show and walk away for more than 4 minutes, the sounds shuts itself off. It doesn't restart when you hit play. The sound quality is ok, but actually not any better than my Samsung Frame TV speakers.",
  'parent_asin': 'B09TKM2R9K'},
 {'preprocessed_data': "Defective Immediately There is a great feature of this TV, as it has the Google Voice Assistant built in. You can either access the Voice Assistant by holding the microphone button down on the remote control, where the remote's mic sends your command to the TV, or by simply (and more conveniently) speaking out loud, saying the Google Wake Words, and then the TV's internal microphone hears you and Google responds. You can control a lot of features just with your voice, without having to touch the remote control. This includes turning the TV off, or muting the sound, or lowering or raising the volume, etc.<br /><br />However, on the TV I received, the internal microphone is dead. Or, it's some other hardware failure. Yes, the microphone switch is set to the ON position. Yes, the setting to allow my voice to control the TV is on. Yes, 2 separate Sony tech support reps accessed my TV via the Remote Access feature and went through everything. It was extensive. Yes, the TV has all the updates, and a factory reset was done. The TV's microphone will not respond at all to the Hey Google or OK Google command.",
  'parent_asin': 'B0B5LSJWJ6'},
 {'preprocessed_data': "Doesn't charge one of the buds Overall great sound and battery just charging issues. This is my Second pair in a few months and same issue.  one bud doesn't connect to the charging dock. It's a constant issue so be ware!!",
  'parent_asin': 'B0C72D4J46'},
 {'preprocessed_data': 'Perfect. Nice looking! Very attractive. Fit great.',
  'parent_asin': 'B0BPTCJD24'},
 {'preprocessed_data': 'Works for me I’m not really an audiophile but I will say the sound from these seems adequate but not life changing. I will use them for audiobooks and watching movies when I don’t want to disturb my husband. For those purposes I think these will be great. I just got them and they’re easy to pair without the instructions. I cannot speak to the durability or battery life yet but I’ll update. I have never in my life been able to get a pair of earbuds to go in let alone stay in my ears. This is a great new technology for me. I’ll probably invest in a high end pair in the future:',
  'parent_asin': 'B0BQLV7TSJ'},

In [40]:
len(data_to_embed_reviews)

122840

In [42]:
text_to_embed_reviews = [item["preprocessed_data"] for item in data_to_embed_reviews]

In [43]:
text_to_embed_reviews

["Nixplay 10.1 touch screen digital picture frame I purchased this digital frame on a treasure truck deal - it  works.  You will have to load the app and follow directions to bluetooth transfer pics you choose from your gallery to the frame.  I purchased an additional memory chip - but it turns out there is no place to install the chip so don't waste your time there.  You can set a regular time to 'run' the frame or manually turn it off and/or on.  You can 'shuffle' OR play all your uploaded pics.  You do not get to choose the 'fade' that happens between pics, but you do get to choose how long each pic stays on the frame before moving to the next pic. Picture quality is pretty good - about as good as the pics you download on to it.  It's close to an 8x10 frame.  Not sure why they call it a 'touch screen' cause I can't figure out what you can do by touching the screen - but ok. It comes with charging cord, regular plug in - there appears to be a mini USB port, but I haven't tried it.  Having said all this I never hesitate to update my reviews should new info seem useful.",
 "Great so far... Speedy delivery, great sound and a great warranty... Let's see how it lasts will update if anything changes.",
 'Set up is not that easy. Nice looking set but installation instructions are not well made.',
 "Waste of money Very unhappy with this keyboard, it would slip and slide all over my keyboard tray., and  I had to look carefully to locate some keys that had been moved around a bit.  The mouse, however, was awesome, so for that reason I'm keeping the product and will use only for emergencies. .",
 'Nice Work great',
 "Works I don't like the look, but it does the job.<br />**********update************<br />After using this a while I decided to buy one of these for my mom. The one she had was a real pain in the wherever!<br />We're both pleased with the swivel capability....it's something I'd always complained about on my old one that didn't swivel, which made a cramped area or not being able to use an outlet because the plug-end of cord was oversized.<br />I've also changed my 4 star to a five...",
 'Great tv mount I used this to mount a 65” fire tv. Took me about an hour from start to finish. Instructions are fine and if your generally a handy person it shouldn’t be a difficult job. I did get some help when I put the TV on, so not a full one person job. Work well and is very adjustable. Overall very pleased.',
 'Great AirTag holder Works great and is very durable. Protects the AirTag well and easily clips on to backpack or can be added to keychain. It’s also nice looking.',
 'Decent I could not get the holder that holds the monitor to stay up. It kept sliding down. Others reviewed it well, so worth trying, just not for me.',
 'Worst cord ever Worst cord ever. The first one I bought wouldn’t plug in correctly and I could only hear sound on one side. They replaced it and here we are, only 2 months later and it’s already not working. Don’t even waste your $10.',
 'Four Bays Are Convenient When Searching Drives From Retired PCs I have a collection of old SATA drives from retired (and now recycled) desktop PCs.  I use this SABRENT USB 3.0 FOUR-BAY 2.5” HARD DRIVE DOCKING STATION WITH FAN (DS-4SSD) to see into the 2.5” (slender) drives, and to occasionally copy off a file that wasn’t transferred when I set up the replacement PCs.  It’s convenient to have the four bays available when I’m not sure which drive contains the file I’m seeking.  I can set up four drives at once to speed the process.<br /><br />In my experience, Sabrent products always perform well, and they’re always reasonably priced.  They deliver good value for the money.',
 'Two USB drives failed to work. First item failed to work  a replacement was sent and it failed to also work.',
 '🙂 🙂',
 'greta for eery day use and the bass was solid. for the price point it is great as I can use it for my spin classes, walking around [ there is no noise cancellation, which is perfecter jungle living as you need to be aware of the surroundings], and so easy to set up.  I was able to login into multiple devices, but you need to reconnect if you do that, otherwise it will connect to the last device it was bluetooth connected to.<br /><br />I accidentally dropped this into cup of cold water and it still worked as the seals are pretty tight.  battery charge was excellent as long as you remember to with it off after use.  charge time as fast and thank goodness it uses the modern C connection design.  love it.',
 'Great Looking and Functioning Cable I am super happy with this cable, mostly because it looks great!  I have to admit we do not push the speed capabilities with any of our equipment, but it works perfectly well between a PS4 and our big TV.  The cable hangs much better from the back of the TV and just plain looks good.  I wish I could match all our cable to this wonderfully neutral, braided gray.  Absolutely perfect!',
 "Beefy but bombastic. What a superb charger! I used this to replace my Amazon-brand brick, which, while it was great, needed to retire (I could hear rattling inside). This is about 1/3 larger than my previous charger, but still fits in my electronics organizer. The cable it comes with is also fantastic; it's the perfect length to keep my computer charged from the wall, and it's braided--yay for braids!<br /><br />There are two USB-C ports with different charging power. The weaker one won't charge if it's not powerful enough, which I realized when trying to charge my MacBook. That's pretty cool because I can charge two items at once, one with a bigger battery and one with a smaller. There's also a USB-A port that can be used at the same time. I notice a dip in charging power when all three ports are used, but that's kind of assumed considering it's used to charge three items at once.",
 "As a backpack organizer, it fits my needs (currently). I don't use this as a laptop sleeve. Instead, I got this because I thought I could use it as a backpack organizer. I carry various notebooks, writing, and drawing supplies with me. I'm not an artist by any means, but I like to journal using different media. Having them loose in my backpack didn't make it easy to find things or have everything in one organized location. This sleeve drastically reduced clutter and makes it faster and easier for me to journal.<br /><br />Currently, it holds my journal, a soft writing mat, my Sonnenleder pencil case, a few fountain pens, a whiteboard notebook, and some markers (dry-erase, Sakura, permanent). It's a tight squeeze, with the front pocket, but overall I have no worries of anything being damaged. In fact, I feel everything is more secure in this. I also love that there are pockets to tuck the handles; I use one only just to pull the sleeve out of my backpack.<br /><br />The front pocket sometimes gets caught in my backpack when I take it out. There's a bit of fabric on the cover of the front pocket so as to conceal the zipper; I wish there wasn't as much excess fabric, or at least some way to stick it closer to the sleeve (like some Velcro or something).<br /><br />But now, instead of looking for and taking out a bunch of things from my backpack, I just pull this out and everything is one, easy-to-locate space.",
 'not too curved perfect size perfect curve i love it very crisp',
 'sturdy great and sturdy and can handle a ton of weight and a couple moves!',
 "Superb value! Awesome color, really stands out when your looking for the cord plus the length is good. So far no issues while charging.<br />I'm happy 😊",
 'Multiple outlets Easy to install, just plug in and screw it in. Plus the outlets move to make room for larger cords.',
 "Should have found this sooner Streamlined way to ad additional outlets versus other products.  Works fine & plugs go in & pull out easily, but don't get knocked out.",
 'Earbuds Great product',
 '4 🌟 Nice for the price',
 "Great on Laptop's I work at home. And it was getting harder and harder to hear the people in the officer. So far, its been working really well. I even had to turn down the volume. I think this great. And the price was great too!",
 'Worth the money spent !! I just recieved the item, and have proceeded touge them the sound quality is excellent.',
 'Will buy again. The ear hook is not adjustable to individual ear sizes. I used the earbuds for everyday functions due to ambulating with crutches daily.',
 "Listing specifically what it dose Beed 1 in 2 out. Description didn't say it was 2 in 1 out",
 'Great pallet Perfect for water colors!',
 'Portable, Quality Means for Listening to Music I like listening to music when I spend time in my backyard. I used to rely on my alexa for this purpose, but more often than not, the volume and clarity were not that good. A portable Bluetooth speaker was the answer and I found just what I needed with this Bluetooth, from Tpone.<br /><br />What you get with this Bluetooth is a portable, chargeable speaker with that offers up to 18 hours of playback on a single charge. Getting it fully charged will take time, but after that, it’s a matter of pairing it with the Bluetooth on your phone. In about two minutes, it will be ready for use.<br /><br />The sound quality you get with this Bluetooth speaker is quite good. I like the bass, and for my needs, the volume is sufficient. It’s not powerful enough to blast you away, but for what I need, the volume level works. I use it mostly when I sit on my back patio and/or jump in the pool. I don’t need extreme volume, so this works. There is a plus and minus button on the unit that at first seem like volume controls, but they are not. If you push these, the music will either advance forward or backward to the next song on the list. The volume is controlled by your phone or whatever device you have paired.<br /><br />There are different colored lights on this speaker that react to the music, adding to the visuals. Again, for my needs, I really don’t care about the lights. But I can see how this could certainly add to the coolness factor for some people. The added colors and the way they react to the intensity of the music is a nice addition. Oh, and I like that I can use this to charge my phone. If a phone is paired, it could drain the phone’s power quickly while you play music. You can easily counter this by plugging your phone directly into the unit, helping to keep your phone charged.<br /><br />Having the means to listen to music is an ongoing need for me. Whether I am listening to music in my backyard or taking a trip to a nearby beach, I need to be able to play my tunes and the easiest way is to use a portable Bluetooth speaker. This Bluetooth from Tpone delivers on most all counts. The easy pairing, the bass, and the overall sound quality make this an easy winner and an excellent Bluetooth choice.',
 "Good cables! I needed good cables to run my phone to my new car, it made a huge difference when I hooked up these cables. I'm not a techy. Just saying it mattered a lot!",
 "No data connection for Pixel 6 Just received today.  Neither of the two let's me connect to transfer data.  I can't say if it works for charging, but I bought for both data and charging, so it's a no go for me.",
 'Cruise Worthy Worked great, cruise personnel didnt balk about it as it is wall based and does not have any wires for extending',
 'Fits nice wish they  glowed in the dark like they said Very nice fit to my controllers only wish they actually glowed in the dark like they said they did, but they do the job they where meant to do.',
 "Does the Job I like the Amazon brand cloth covers. They have a nice grippy texture are easy to clean and fit the device well. The magnetic wake on opening feature works well. I do wish there was a better variety of colors maybe designs or patterns but that's just not super important.",
 'Great fill lights I used AI bought these for fill lights.  They can provide the equivalent of a 20 W incandescent light, which is plenty of light with modern DSLRs.  One or two can fill int he shadows when shooting in low light or backlit situations.  battery life is excellent with no problems getting over 90 minutes of life at full power and much longer with even a small decrease in output.  If I had any ideas for improvement, it would be to have presets for common light sources (daylight, tungsten, etc.) to better match the primary light source.  The value of the unit is great, and I highly recommend it.',
 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
 'Works great Amazing cable for playing games',
 'Better than I thought I am really enjoying the sound quality from these as I needed to switch from a corded headset to something wireless. This is Bluetooth but the Bluetooth chip works well and doesn’t seem to have issue where it disconnects from my laptop and connects to my phone (I’ve had this with a few speakers).<br /><br />The mic works great as I do user testing and the sound quality is important for good feedback as a tester.<br /><br />I was pleasantly surprised to find out that the chip isn’t needed unless Bluetooth isn’t available on the device. There was no issue with connectivity either as my laptop recognizes the USB Bluetooth chip and automatically paired with the headset. A plus for me since my laptop tends to lag.<br /><br />The headset has a good/decent look to it. The earpieces are squishy and comfortable. The headset adjusts easily. The plastic seems to be of decent quality so putting them on and taking off repeatedly should not be an issue. Very pleased overall.',
 'No me gusto mucho No me gusta porque no puedo conectarla a la laptop para usarla  como web cam y grabar',
 'Great little fan Perfect for work, can use with usb or block (not included)',
 "Next to useless After a week, I am giving up on this sound bar and going back to my tv speakers. It worked well for 24 hours and then began to have glitches.<br /><br />The optic connection is ok, but the included cable is loose and doesn't want to stay out. The outlet plug is huge and the cord is short - there's no reason for that.<br /><br />Mostly though, the remote and overall functionality is driving me nuts. The power buttons on the remote do not work at all. I have to manually turn on the sound bar with a button on the side. If I pause a show and walk away for more than 4 minutes, the sounds shuts itself off. It doesn't restart when you hit play. The sound quality is ok, but actually not any better than my Samsung Frame TV speakers.",
 "Defective Immediately There is a great feature of this TV, as it has the Google Voice Assistant built in. You can either access the Voice Assistant by holding the microphone button down on the remote control, where the remote's mic sends your command to the TV, or by simply (and more conveniently) speaking out loud, saying the Google Wake Words, and then the TV's internal microphone hears you and Google responds. You can control a lot of features just with your voice, without having to touch the remote control. This includes turning the TV off, or muting the sound, or lowering or raising the volume, etc.<br /><br />However, on the TV I received, the internal microphone is dead. Or, it's some other hardware failure. Yes, the microphone switch is set to the ON position. Yes, the setting to allow my voice to control the TV is on. Yes, 2 separate Sony tech support reps accessed my TV via the Remote Access feature and went through everything. It was extensive. Yes, the TV has all the updates, and a factory reset was done. The TV's microphone will not respond at all to the Hey Google or OK Google command.",
 "Doesn't charge one of the buds Overall great sound and battery just charging issues. This is my Second pair in a few months and same issue.  one bud doesn't connect to the charging dock. It's a constant issue so be ware!!",
 'Perfect. Nice looking! Very attractive. Fit great.',
 'Works for me I’m not really an audiophile but I will say the sound from these seems adequate but not life changing. I will use them for audiobooks and watching movies when I don’t want to disturb my husband. For those purposes I think these will be great. I just got them and they’re easy to pair without the instructions. I cannot speak to the durability or battery life yet but I’ll update. I have never in my life been able to get a pair of earbuds to go in let alone stay in my ears. This is a great new technology for me. I’ll probably invest in a high end pair in the future:',
 'Compact adapter. Does the job. Per the recommended usage, I bought this to take on cruises.  Saved me from having to bring a small extension cord with the larger unit I used to take along with me.  Fit in the socket above the counter in the room, and I did not have to plug in and then unplug each time I left the stateroom.  Charged the phones and iPads with any hassle.  A bit spendy price, but I did not have to make multiple payments, so I am happy with the unit.  Lol.',
 'Space saver surge protector. I bought this to help reduce the amount of space needed behind my TV stand.  It does the job, and reviews were positive about the surge protection.  That was why I purchased this unit as it actually was replacing a large Monster Cable Audio/Video Surge protection component that I had bought about 15 years ago with my large 65&#34; rear projection TV screen.  That had finally started to fail in some of the plug ins, and I was also reducing the items plugged into it.  Now I just have the TV, sound bar, DVR, and DVD player that needed to be plugged in.  This works fine so far. Will update if anything changes.<br /><br />On a side note, I had thought I would be able to remove the cover to my wall plus as this screws into the wall plug space, but the gap on top of the unit does not cover the opening in the wall, so I had to put the cover back on, but just removed the screw that attached the cover and used the screw to attached this unit into the outlet.',
 "Failed in 1 year Was great while it lasted then suddenly it wouldn't connect and all the drives in it were absent.  I tried updating and reinstalling usb drivers to no avail.  So basically it costs about 8  bucks a month and then without warning, it's gone, have to buy a new one.",
 'It’s great with a pocket hold’s well hard plastic holding the iPad Great with pocket holds well plastic back to hold iPad',
 'So-so This are cute and the size stays in but the sound is very tinny. We will keep them but they are not the best, by a long shot.',
 'Switch works perfectly for two gaming stations & one TV. Really fast delivery Excellent switch, works perfectly between the PS3 & PS4 on one TV.',

In [44]:
embeddings = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 122840
Processed 1000 of 122840
Processed 1500 of 122840
Processed 2000 of 122840
Processed 2500 of 122840
Processed 3000 of 122840
Processed 3500 of 122840
Processed 4000 of 122840
Processed 4500 of 122840
Processed 5000 of 122840
Processed 5500 of 122840
Processed 6000 of 122840
Processed 6500 of 122840
Processed 7000 of 122840
Processed 7500 of 122840
Processed 8000 of 122840
Processed 8500 of 122840
Processed 9000 of 122840
Processed 9500 of 122840
Processed 10000 of 122840
Processed 10500 of 122840
Processed 11000 of 122840
Processed 11500 of 122840
Processed 12000 of 122840
Processed 12500 of 122840
Processed 13000 of 122840
Processed 13500 of 122840
Processed 14000 of 122840
Processed 14500 of 122840
Processed 15000 of 122840
Processed 15500 of 122840
Processed 16000 of 122840
Processed 16500 of 122840
Processed 17000 of 122840
Processed 17500 of 122840
Processed 18000 of 122840
Processed 18500 of 122840
Processed 19000 of 122840
Processed 19500 of 122840
Processed 20000 of 122840
Processed 20500 of 122840
Processed 21000 of 122840
Processed 21500 of 122840
Processed 22000 of 122840
Processed 22500 of 122840
Processed 23000 of 122840
Processed 23500 of 122840
Processed 24000 of 122840
Processed 24500 of 122840
Processed 25000 of 122840
Processed 25500 of 122840
Processed 26000 of 122840
Processed 26500 of 122840
Processed 27000 of 122840
Processed 27500 of 122840
Processed 28000 of 122840
Processed 28500 of 122840
Processed 29000 of 122840
Processed 29500 of 122840
Processed 30000 of 122840
Processed 30500 of 122840
Processed 31000 of 122840
Processed 31500 of 122840
Processed 32000 of 122840
Processed 32500 of 122840
Processed 33000 of 122840
Processed 33500 of 122840
Processed 34000 of 122840
Processed 34500 of 122840
Processed 35000 of 122840
Processed 35500 of 122840
Processed 36000 of 122840
Processed 36500 of 122840
Processed 37000 of 122840
Processed 37500 of 122840
Processed 38000 of 122840
Processed 38500 of 122840
Processed 39000 of 122840
Processed 39500 of 122840
Processed 40000 of 122840
Processed 40500 of 122840
Processed 41000 of 122840
Processed 41500 of 122840
Processed 42000 of 122840
Processed 42500 of 122840
Processed 43000 of 122840
Processed 43500 of 122840
Processed 44000 of 122840
Processed 44500 of 122840
Processed 45000 of 122840
Processed 45500 of 122840
Processed 46000 of 122840
Processed 46500 of 122840
Processed 47000 of 122840
Processed 47500 of 122840
Processed 48000 of 122840
Processed 48500 of 122840
Processed 49000 of 122840
Processed 49500 of 122840
Processed 50000 of 122840
Processed 50500 of 122840
Processed 51000 of 122840
Processed 51500 of 122840
Processed 52000 of 122840
Processed 52500 of 122840
Processed 53000 of 122840
Processed 53500 of 122840
Processed 54000 of 122840
Processed 54500 of 122840
Processed 55000 of 122840
Processed 55500 of 122840
Processed 56000 of 122840
Processed 56500 of 122840
Processed 57000 of 122840
Processed 57500 of 122840
Processed 58000 of 122840
Processed 58500 of 122840
Processed 59000 of 122840
Processed 59500 of 122840
Processed 60000 of 122840
Processed 60500 of 122840
Processed 61000 of 122840
Processed 61500 of 122840
Processed 62000 of 122840
Processed 62500 of 122840
Processed 63000 of 122840
Processed 63500 of 122840
Processed 64000 of 122840
Processed 64500 of 122840
Processed 65000 of 122840
Processed 65500 of 122840
Processed 66000 of 122840
Processed 66500 of 122840
Processed 67000 of 122840
Processed 67500 of 122840
Processed 68000 of 122840
Processed 68500 of 122840
Processed 69000 of 122840
Processed 69500 of 122840
Processed 70000 of 122840
Processed 70500 of 122840
Processed 71000 of 122840
Processed 71500 of 122840
Processed 72000 of 122840
Processed 72500 of 122840
Processed 73000 of 122840
Processed 73500 of 122840
Processed 74000 of 122840
Processed 74500 of 122840
Processed 75000 of 122840
Processed 75500 of 122840
Processed 76000 of 122840
Processed 76500 of 122840
Processed 77000 of 122840
Processed 77500 of 122840
Processed 78000 of 122840
Processed 78500 of 122840
Processed 79000 of 122840
Processed 79500 of 122840
Processed 80000 of 122840
Processed 80500 of 122840
Processed 81000 of 122840
Processed 81500 of 122840
Processed 82000 of 122840
Processed 82500 of 122840
Processed 83000 of 122840
Processed 83500 of 122840
Processed 84000 of 122840
Processed 84500 of 122840
Processed 85000 of 122840
Processed 85500 of 122840
Processed 86000 of 122840
Processed 86500 of 122840
Processed 87000 of 122840
Processed 87500 of 122840
Processed 88000 of 122840
Processed 88500 of 122840
Processed 89000 of 122840
Processed 89500 of 122840
Processed 90000 of 122840
Processed 90500 of 122840
Processed 91000 of 122840
Processed 91500 of 122840
Processed 92000 of 122840
Processed 92500 of 122840
Processed 93000 of 122840
Processed 93500 of 122840
Processed 94000 of 122840
Processed 94500 of 122840
Processed 95000 of 122840
Processed 95500 of 122840
Processed 96000 of 122840
Processed 96500 of 122840
Processed 97000 of 122840
Processed 97500 of 122840
Processed 98000 of 122840
Processed 98500 of 122840
Processed 99000 of 122840
Processed 99500 of 122840
Processed 100000 of 122840
Processed 100500 of 122840
Processed 101000 of 122840
Processed 101500 of 122840
Processed 102000 of 122840
Processed 102500 of 122840
Processed 103000 of 122840
Processed 103500 of 122840
Processed 104000 of 122840
Processed 104500 of 122840
Processed 105000 of 122840
Processed 105500 of 122840
Processed 106000 of 122840
Processed 106500 of 122840
Processed 107000 of 122840
Processed 107500 of 122840
Processed 108000 of 122840
Processed 108500 of 122840
Processed 109000 of 122840
Processed 109500 of 122840
Processed 110000 of 122840
Processed 110500 of 122840
Processed 111000 of 122840
Processed 111500 of 122840
Processed 112000 of 122840
Processed 112500 of 122840
Processed 113000 of 122840
Processed 113500 of 122840
Processed 114000 of 122840
Processed 114500 of 122840
Processed 115000 of 122840
Processed 115500 of 122840
Processed 116000 of 122840
Processed 116500 of 122840
Processed 117000 of 122840
Processed 117500 of 122840
Processed 118000 of 122840
Processed 118500 of 122840
Processed 119000 of 122840
Processed 119500 of 122840
Processed 120000 of 122840
Processed 120500 of 122840
Processed 121000 of 122840
Processed 121500 of 122840
Processed 122000 of 122840
Processed 122500 of 122840
Processed 123000 of 122840

In [45]:
len(embeddings)

122840

In [46]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding
            },
            payload=data
        )
    )
    i += 1

In [47]:
pointstructs[0].vector

{'text-embedding-3-small': [0.0068359375,
  0.01453399658203125,
  -0.055877685546875,
  -0.019622802734375,
  -0.01161956787109375,
  -0.03424072265625,
  0.0307769775390625,
  0.032440185546875,
  -0.0233001708984375,
  -0.025634765625,
  0.01971435546875,
  -0.01543426513671875,
  -0.042144775390625,
  0.01568603515625,
  0.0230560302734375,
  -0.034454345703125,
  -0.027008056640625,
  -0.038848876953125,
  -0.0162811279296875,
  0.0150604248046875,
  0.03546142578125,
  0.0186614990234375,
  0.018798828125,
  -0.052001953125,
  0.027679443359375,
  -0.004909515380859375,
  -0.01291656494140625,
  -0.0202789306640625,
  0.0265045166015625,
  0.03204345703125,
  -0.087890625,
  -0.0201873779296875,
  0.0003254413604736328,
  -0.05615234375,
  -0.01175689697265625,
  -0.048583984375,
  0.012969970703125,
  -0.031402587890625,
  -0.045684814453125,
  -0.023345947265625,
  0.0265045166015625,
  0.029998779296875,
  0.017852783203125,
  -0.01409149169921875,
  0.0275726318359375,
  -0.019744873046875,
  -0.060150146484375,
  -0.0213165283203125,
  -0.041748046875,
  0.051422119140625,
  -0.014739990234375,
  0.045166015625,
  -0.049407958984375,
  -0.027069091796875,
  -0.01462554931640625,
  -0.000743865966796875,
  0.01346588134765625,
  -0.0178375244140625,
  0.01346588134765625,
  0.0271759033203125,
  0.027069091796875,
  -0.061767578125,
  0.0184478759765625,
  0.0772705078125,
  -0.0306549072265625,
  -0.01441192626953125,
  -0.02606201171875,
  0.00968170166015625,
  -0.050506591796875,
  -0.0181884765625,
  0.011199951171875,
  -0.035888671875,
  -0.0447998046875,
  -0.039703369140625,
  0.007720947265625,
  0.07098388671875,
  0.0231475830078125,
  0.0003314018249511719,
  0.045013427734375,
  0.0298309326171875,
  -0.01419830322265625,
  0.005847930908203125,
  -0.040435791015625,
  0.009246826171875,
  -0.07012939453125,
  0.0228118896484375,
  0.004070281982421875,
  -0.0391845703125,
  -0.02813720703125,
  -0.0239105224609375,
  -0.01123046875,
  0.01158905029296875,
  0.01413726806640625,
  0.0321044921875,
  -0.007396697998046875,
  -0.02447509765625,
  -0.02496337890625,
  -0.01105499267578125,
  0.0143890380859375,
  0.0082550048828125,
  -0.0191497802734375,
  0.01947021484375,
  -0.041229248046875,
  -0.05572509765625,
  0.034027099609375,
  -0.06451416015625,
  -0.0181427001953125,
  0.024169921875,
  0.0181884765625,
  0.07598876953125,
  -0.10400390625,
  -0.053619384765625,
  0.01425933837890625,
  0.057952880859375,
  -0.036712646484375,
  -0.034912109375,
  0.0244903564453125,
  0.0399169921875,
  -0.0133056640625,
  0.011566162109375,
  0.03173828125,
  0.01016998291015625,
  -0.0147247314453125,
  0.01336669921875,
  -0.01169586181640625,
  -0.03436279296875,
  -0.01708984375,
  0.01434326171875,
  -0.01476287841796875,
  -0.00830078125,
  0.0030345916748046875,
  -0.06121826171875,
  0.00476837158203125,
  -0.025848388671875,
  -0.0504150390625,
  0.005817413330078125,
  -0.00659942626953125,
  0.006336212158203125,
  -0.034881591796875,
  -0.0257568359375,
  -0.01448822021484375,
  -0.021209716796875,
  0.0196990966796875,
  -0.018310546875,
  0.0307464599609375,
  0.015289306640625,
  0.03912353515625,
  -0.0220489501953125,
  -0.01947021484375,
  0.014068603515625,
  0.00466156005859375,
  0.017578125,
  0.0256500244140625,
  -0.026275634765625,
  0.0305023193359375,
  -0.02447509765625,
  0.026519775390625,
  0.033935546875,
  -0.0643310546875,
  0.040435791015625,
  -0.01507568359375,
  -0.029815673828125,
  -0.015411376953125,
  -0.01497650146484375,
  -0.027435302734375,
  0.049835205078125,
  0.0106353759765625,
  -0.0289764404296875,
  -0.0626220703125,
  0.06817626953125,
  -0.018402099609375,
  -0.01265716552734375,
  -0.016845703125,
  0.014892578125,
  -0.015899658203125,
  -0.01971435546875,
  0.0265655517578125,
  -0.029571533203125,
  -0.0224609375,
  0.02093505859375,
  -0.0467529296875,
  -0.049774169921875,
  -0.01160430908203125,
  0.04461669921875,
  -0.0203704833984375,
  -0.0236663818359375,
  -0.0113677978515625,
  0.03497314453125,
  -0.027008056640625,
  -0.0125732421875,
  0.00548553466796875,
  0.07464599609375,
  -0.0210418701171875,
  -0.0239105224609375,
  -0.045440673828125,
  -0.051422119140625,
  0.036407470703125,
  0.034454345703125,
  -0.027679443359375,
  0.0203704833984375,
  0.007717132568359375,
  0.0088348388671875,
  0.00807952880859375,
  0.046844482421875,
  -0.0282745361328125,
  -0.009735107421875,
  -0.0140380859375,
  -0.0038967132568359375,
  -0.0149383544921875,
  -0.01392364501953125,
  -0.0063018798828125,
  -0.01029205322265625,
  0.0055389404296875,
  -0.047393798828125,
  -0.00714111328125,
  0.0009503364562988281,
  0.039154052734375,
  0.049591064453125,
  -0.012481689453125,
  0.047821044921875,
  -0.049957275390625,
  0.001636505126953125,
  0.0217742919921875,
  -0.036346435546875,
  0.011962890625,
  0.021728515625,
  -0.032379150390625,
  0.0237274169921875,
  -0.021514892578125,
  0.00798797607421875,
  0.017547607421875,
  0.0254364013671875,
  -0.040740966796875,
  -0.021575927734375,
  0.00038504600524902344,
  -0.004425048828125,
  -0.0271453857421875,
  -0.033203125,
  -0.0284423828125,
  0.03741455078125,
  -0.041107177734375,
  0.033782958984375,
  -0.00873565673828125,
  -0.005275726318359375,
  -0.0083465576171875,
  -0.0258941650390625,
  -0.0271453857421875,
  -0.069580078125,
  0.04107666015625,
  -0.003711700439453125,
  0.0026683807373046875,
  -0.01262664794921875,
  -0.0099029541015625,
  -0.034454345703125,
  0.01131439208984375,
  -0.04693603515625,
  -0.0035724639892578125,
  -0.017333984375,
  -0.0149383544921875,
  -0.04046630859375,
  0.01322174072265625,
  -0.0236968994140625,
  -0.033447265625,
  -0.0321044921875,
  0.005062103271484375,
  0.03509521484375,
  0.007537841796875,
  0.0264434814453125,
  -0.023529052734375,
  0.0112457275390625,
  0.040191650390625,
  -0.0022792816162109375,
  -0.0633544921875,
  0.022857666015625,
  0.0162506103515625,
  -0.0186920166015625,
  -0.035675048828125,
  -0.01076507568359375,
  0.01111602783203125,
  0.0017957687377929688,
  -0.00859832763671875,
  -0.01338958740234375,
  -0.03704833984375,
  0.022705078125,
  0.004459381103515625,
  0.007549285888671875,
  0.0440673828125,
  0.0024509429931640625,
  0.02813720703125,
  0.03704833984375,
  -0.0229644775390625,
  -0.028106689453125,
  -0.021270751953125,
  0.01265716552734375,
  -0.011962890625,
  0.0022830963134765625,
  -0.03021240234375,
  0.0361328125,
  -0.01172637939453125,
  -0.01419830322265625,
  -0.0002460479736328125,
  -0.0196990966796875,
  -0.00919342041015625,
  -0.0230255126953125,
  -0.0260162353515625,
  0.0447998046875,
  -0.02813720703125,
  0.01155853271484375,
  0.037506103515625,
  -0.0078277587890625,
  0.0296173095703125,
  0.0208282470703125,
  0.044464111328125,
  -0.045867919921875,
  0.0229949951171875,
  0.01413726806640625,
  0.055816650390625,
  0.00568389892578125,
  -0.0088348388671875,
  -0.0504150390625,
  0.048309326171875,
  -0.0257110595703125,
  0.006420135498046875,
  0.00533294677734375,
  -0.033966064453125,
  0.0008978843688964844,
  0.0174713134765625,
  -0.012298583984375,
  0.027679443359375,
  0.00902557373046875,
  0.0012903213500976562,
  -0.0173187255859375,
  0.006443023681640625,
  0.03192138671875,
  0.01499176025390625,
  -0.025848388671875,
  0.004123687744140625,
  -0.0279083251953125,
  -0.03173828125,
  -0.0115509033203125,
  0.0079345703125,
  -0.0341796875,
  -0.0006771087646484375,
  0.003997802734375,
  -0.0153045654296875,
  -0.01436614990234375,
  -0.036224365234375,
  0.0213623046875,
  0.0275726318359375,
  -0.02508544921875,
  0.0012149810791015625,
  0.011810302734375,
  0.0200653076171875,
  -0.032928466796875,
  0.0552978515625,
  -0.0035610198974609375,
  -0.038848876953125,
  0.0182037353515625,
  -0.08782958984375,
  -0.01250457763671875,
  -0.029449462890625,
  0.0054931640625,
  0.024810791015625,
  0.0229339599609375,
  0.006694793701171875,
  0.01177215576171875,
  -0.026275634765625,
  -0.0214691162109375,
  -0.029876708984375,
  -0.01183319091796875,
  0.0272216796875,
  0.03887939453125,
  0.0253143310546875,
  0.038055419921875,
  -0.0191650390625,
  -0.064208984375,
  0.032318115234375,
  -0.000797271728515625,
  -0.0202789306640625,
  -0.0124664306640625,
  0.006679534912109375,
  0.0219879150390625,
  0.061981201171875,
  -0.0081634521484375,
  0.015167236328125,
  -0.0214080810546875,
  0.00971221923828125,
  -0.0004115104675292969,
  -0.016876220703125,
  0.00188446044921875,
  0.05108642578125,
  -0.0261688232421875,
  -0.04351806640625,
  -0.0333251953125,
  -0.0274505615234375,
  0.045928955078125,
  0.0178375244140625,
  0.002613067626953125,
  0.02923583984375,
  0.017608642578125,
  0.0160369873046875,
  -0.03228759765625,
  -0.0278472900390625,
  0.0186920166015625,
  -0.048553466796875,
  -0.0255126953125,
  -0.0109710693359375,
  -0.0165557861328125,
  0.0169677734375,
  0.018890380859375,
  -0.0232391357421875,
  -0.0692138671875,
  0.06890869140625,
  -0.010955810546875,
  0.019439697265625,
  -0.0221405029296875,
  -0.02056884765625,
  0.022186279296875,
  0.0037689208984375,
  0.0045166015625,
  -0.01311492919921875,
  -0.027862548828125,
  0.00800323486328125,
  -0.0335693359375,
  -0.038818359375,
  0.002193450927734375,
  0.02471923828125,
  -0.01092529296875,
  0.036590576171875,
  -0.0723876953125,
  -0.0013265609741210938,
  0.0430908203125,
  0.0264434814453125,
  -0.007778167724609375,
  0.0025177001953125,
  -0.003078460693359375,
  -0.03277587890625,
  0.0087738037109375,
  -0.02447509765625,
  -0.01094818115234375,
  -0.0089569091796875,
  0.024627685546875,
  0.028411865234375,
  0.006359100341796875,
  -0.0127410888671875,
  0.03570556640625,
  -0.0214996337890625,
  0.037384033203125,
  -0.035797119140625,
  -0.041717529296875,
  -0.060150146484375,
  0.0127105712890625,
  -0.0164947509765625,
  0.044525146484375,
  0.0164337158203125,
  -0.001575469970703125,
  0.0285797119140625,
  -0.0258331298828125,
  -0.028076171875,
  -0.0185699462890625,
  -0.0379638671875,
  0.0207061767578125,
  0.01396942138671875,
  0.049102783203125,
  0.00811004638671875,
  0.0601806640625,
  -0.0190887451171875,
  0.0548095703125,
  0.0253143310546875,
  -0.02386474609375,
  -0.006610870361328125,
  0.036529541015625,
  0.01560211181640625,
  0.0167388916015625,
  -0.01035308837890625,
  0.021942138671875,
  0.00946807861328125,
  0.0256805419921875,
  0.01013946533203125,
  -0.037384033203125,
  -0.01849365234375,
  0.0168304443359375,
  -0.030242919921875,
  -0.010467529296875,
  0.009735107421875,
  0.0946044921875,
  0.0121002197265625,
  -0.04376220703125,
  -0.057891845703125,
  -0.043121337890625,
  -0.035125732421875,
  -0.00405120849609375,
  -0.004444122314453125,
  -0.01123046875,
  -0.013275146484375,
  0.0001442432403564453,
  0.01345062255859375,
  -0.0133056640625,
  -0.030792236328125,
  0.04254150390625,
  -0.0193634033203125,
  0.076171875,
  -0.0163116455078125,
  -0.0176544189453125,
  -0.03973388671875,
  -0.0214996337890625,
  -0.0145111083984375,
  0.033233642578125,
  -0.01403045654296875,
  -0.03021240234375,
  0.0155029296875,
  0.022552490234375,
  -0.0245361328125,
  0.021881103515625,
  -0.02685546875,
  0.004878997802734375,
  0.01134490966796875,
  0.040374755859375,
  -0.027008056640625,
  0.01739501953125,
  -0.032257080078125,
  -0.0124359130859375,
  0.0521240234375,
  -0.05303955078125,
  0.0645751953125,
  0.0194091796875,
  -0.045135498046875,
  -0.036956787109375,
  -0.06292724609375,
  0.00185394287109375,
  -0.0113677978515625,
  0.00426483154296875,
  -0.039276123046875,
  0.00359344482421875,
  -0.034088134765625,
  -0.005237579345703125,
  0.0247650146484375,
  0.005290985107421875,
  -0.0273590087890625,
  0.0035915374755859375,
  -0.0140380859375,
  -0.0142669677734375,
  -0.0031147003173828125,
  0.034423828125,
  0.00872802734375,
  -0.00952911376953125,
  -0.006923675537109375,
  -0.0206756591796875,
  -0.02777099609375,
  -0.01177978515625,
  0.00536346435546875,
  -0.0189666748046875,
  0.0209808349609375,
  0.0170135498046875,
  -0.000507354736328125,
  -0.0014142990112304688,
  0.000835418701171875,
  0.00949859619140625,
  0.0294036865234375,
  0.006557464599609375,
  0.01407623291015625,
  -0.006610870361328125,
  0.0258026123046875,
  -0.0155792236328125,
  0.03497314453125,
  0.04144287109375,
  0.01538848876953125,
  -0.01186370849609375,
  -0.002368927001953125,
  0.017425537109375,
  -0.00496673583984375,
  -0.0167388916015625,
  0.00031828880310058594,
  -0.01279449462890625,
  0.032806396484375,
  -0.001209259033203125,
  0.028106689453125,
  0.029876708984375,
  -0.0206451416015625,
  0.0016078948974609375,
  0.00800323486328125,
  -0.061767578125,
  0.0296173095703125,
  -0.0007157325744628906,
  0.00362396240234375,
  0.01141357421875,
  -0.031463623046875,
  -0.041015625,
  0.0472412109375,
  0.0491943359375,
  -0.0038967132568359375,
  -0.0288543701171875,
  -0.056549072265625,
  0.00804901123046875,
  0.01947021484375,
  0.044464111328125,
  -0.00039267539978027344,
  0.0090789794921875,
  -0.02386474609375,
  0.006168365478515625,
  0.0059814453125,
  0.00022852420806884766,
  -0.029815673828125,
  0.01117706298828125,
  0.0154571533203125,
  0.0212860107421875,
  0.005474090576171875,
  0.0038967132568359375,
  -0.0204925537109375,
  -0.02618408203125,
  -0.004566192626953125,
  0.00827789306640625,
  -0.01049041748046875,
  0.0261383056640625,
  -0.020751953125,
  0.0418701171875,
  -0.00799560546875,
  0.007183074951171875,
  0.0190277099609375,
  0.0283050537109375,
  -0.083984375,
  -0.01153564453125,
  -0.019256591796875,
  0.0205841064453125,
  -0.0169830322265625,
  0.0318603515625,
  -0.02398681640625,
  -0.0217437744140625,
  -0.01751708984375,
  -0.0084381103515625,
  0.03765869140625,
  0.00677490234375,
  0.019256591796875,
  0.0255889892578125,
  -0.0023365020751953125,
  0.003108978271484375,
  0.0285186767578125,
  -0.020599365234375,
  0.004306793212890625,
  0.01690673828125,
  0.01056671142578125,
  0.0006170272827148438,
  -0.00550079345703125,
  0.0022373199462890625,
  -0.0015239715576171875,
  0.015899658203125,
  -0.016998291015625,
  -0.003917694091796875,
  -0.0165252685546875,
  -0.01611328125,
  -0.023040771484375,
  -0.007061004638671875,
  0.05975341796875,
  0.0021877288818359375,
  0.0364990234375,
  -0.0110321044921875,
  -0.05108642578125,
  -0.0095672607421875,
  -0.03131103515625,
  -0.00785064697265625,
  0.0029964447021484375,
  0.047515869140625,
  -0.03753662109375,
  0.00534820556640625,
  -0.0199432373046875,
  -0.0249786376953125,
  -0.0023956298828125,
  -0.032501220703125,
  0.01108551025390625,
  0.0189666748046875,
  -0.0108795166015625,
  0.00305938720703125,
  -0.0009713172912597656,
  -0.022735595703125,
  0.00408172607421875,
  -0.0123138427734375,
  0.032958984375,
  -0.018096923828125,
  0.02215576171875,
  -0.01432037353515625,
  -0.0037384033203125,
  0.0084991455078125,
  -0.0248870849609375,
  0.01374053955078125,
  0.0307769775390625,
  -0.00614166259765625,
  0.00194549560546875,
  0.00362396240234375,
  0.0232086181640625,
  -0.0293731689453125,
  0.0062103271484375,
  0.0066680908203125,
  0.0304107666015625,
  -0.018524169921875,
  -0.01305389404296875,
  -0.0277252197265625,
  -0.0011119842529296875,
  -0.025299072265625,
  0.03985595703125,
  -0.04010009765625,
  -0.0009860992431640625,
  0.02264404296875,
  -0.0008878707885742188,
  -0.024169921875,
  -0.01910400390625,
  -0.045013427734375,
  -0.0016574859619140625,
  -0.0126495361328125,
  0.023895263671875,
  -0.002292633056640625,
  -0.0196533203125,
  -0.00984954833984375,
  -0.01263427734375,
  0.044708251953125,
  0.035797119140625,
  0.0013370513916015625,
  -0.01342010498046875,
  0.0229034423828125,
  0.01073455810546875,
  -0.021331787109375,
  0.0009593963623046875,
  0.0222625732421875,
  0.00406646728515625,
  -0.017669677734375,
  -0.007495880126953125,
  -0.019744873046875,
  0.00798797607421875,
  0.01204681396484375,
  0.0015544891357421875,
  0.0290679931640625,
  -0.025390625,
  -0.04058837890625,
  0.0242767333984375,
  0.003993988037109375,
  0.00376129150390625,
  0.016815185546875,
  0.0251312255859375,
  -0.011932373046875,
  0.0020427703857421875,
  -0.0155792236328125,
  -0.005146026611328125,
  0.00926971435546875,
  0.0379638671875,
  0.00901031494140625,
  0.0300750732421875,
  0.002582550048828125,
  -0.014068603515625,
  -0.05535888671875,
  -0.02777099609375,
  -0.047210693359375,
  -0.0030193328857421875,
  0.00887298583984375,
  0.0170745849609375,
  -0.0088653564453125,
  -0.03411865234375,
  0.0165252685546875,
  -0.031494140625,
  -0.0103759765625,
  -0.022064208984375,
  0.007747650146484375,
  0.003513336181640625,
  0.037750244140625,
  -0.01035308837890625,
  0.00601959228515625,
  -0.014404296875,
  -0.0088958740234375,
  -0.0185089111328125,
  -0.006793975830078125,
  -0.0201873779296875,
  -0.019256591796875,
  -0.0245513916015625,
  0.013031005859375,
  0.0091400146484375,
  -0.00038623809814453125,
  0.036407470703125,
  -0.0548095703125,
  0.0001723766326904297,
  -0.00730133056640625,
  0.026641845703125,
  0.0103302001953125,
  -0.01514434814453125,
  -0.0015325546264648438,
  0.00797271728515625,
  -0.0237579345703125,
  0.01305389404296875,
  -0.01934814453125,
  -0.0369873046875,
  0.013946533203125,
  0.00848388671875,
  -0.0284881591796875,
  -0.0057830810546875,
  -0.0206146240234375,
  -0.0029125213623046875,
  0.001708984375,
  0.01409149169921875,
  -0.0277862548828125,
  -0.021331787109375,
  -0.07989501953125,
  -0.01317596435546875,
  0.0015611648559570312,
  -0.0294189453125,
  -0.037384033203125,
  -0.0560302734375,
  -0.00775909423828125,
  0.01078033447265625,
  0.0404052734375,
  -0.0221099853515625,
  -0.0015125274658203125,
  0.0111236572265625,
  0.00614166259765625,
  0.031982421875,
  0.00702667236328125,
  -0.0181884765625,
  0.0526123046875,
  0.004268646240234375,
  0.0257110595703125,
  0.0207061767578125,
  -0.044281005859375,
  0.0164337158203125,
  -0.0073394775390625,
  0.0242919921875,
  -0.035125732421875,
  -0.018157958984375,
  -0.00945281982421875,
  0.00525665283203125,
  0.0095062255859375,
  -0.0242767333984375,
  0.0162353515625,
  -0.00026917457580566406,
  -0.005290985107421875,
  -0.0278167724609375,
  0.0208892822265625,
  0.0255584716796875,
  -0.0295867919921875,
  -0.002105712890625,
  0.0178985595703125,
  -0.0037403106689453125,
  0.0008602142333984375,
  -0.0021820068359375,
  -0.03704833984375,
  -0.00502777099609375,
  0.00122833251953125,
  -0.0232391357421875,
  -0.005664825439453125,
  0.0276947021484375,
  0.0190887451171875,
  -0.0128631591796875,
  0.00958251953125,
  -0.032318115234375,
  -0.014434814453125,
  0.032073974609375,
  -0.01044464111328125,
  -0.0279388427734375,
  0.0013484954833984375,
  -0.00420379638671875,
  -0.0080718994140625,
  0.038909912109375,
  0.0189666748046875,
  0.010833740234375,
  0.037078857421875,
  -0.005153656005859375,
  0.03839111328125,
  -0.004039764404296875,
  0.026885986328125,
  -0.044097900390625,
  -0.006134033203125,
  -0.00672149658203125,
  -0.0439453125,
  0.031494140625,
  0.00998687744140625,
  -0.06488037109375,
  -0.033203125,
  -0.038818359375,
  0.04302978515625,
  -0.003482818603515625,
  -0.006076812744140625,
  -0.006053924560546875,
  -0.031707763671875,
  0.03887939453125,
  0.01024627685546875,
  -0.007312774658203125,
  -0.0302886962890625,
  0.0268402099609375,
  -0.04119873046875,
  -0.0192108154296875,
  0.051116943359375,
  -0.0197601318359375,
  0.01448822021484375,
  0.01412200927734375,
  -0.014892578125,
  -0.01056671142578125,
  -0.028472900390625,
  0.02020263671875,
  -0.01593017578125,
  -0.035919189453125,
  0.0022144317626953125,
  0.0022869110107421875,
  0.02227783203125,
  -0.00342559814453125,
  0.0229339599609375,
  -0.010955810546875,
  -0.00458526611328125,
  -0.0113067626953125,
  -0.00716400146484375,
  -0.024444580078125,

In [48]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-reviews-collection-01",
        points=batch,
        wait=True
    )
    print(f"Processed {counter * batch_size_qdrant} of {len(pointstructs)}")
    counter += 1

Processed 100 of 122840
Processed 200 of 122840
Processed 300 of 122840
Processed 400 of 122840
Processed 500 of 122840
Processed 600 of 122840
Processed 700 of 122840
Processed 800 of 122840
Processed 900 of 122840
Processed 1000 of 122840
Processed 1100 of 122840
Processed 1200 of 122840
Processed 1300 of 122840
Processed 1400 of 122840
Processed 1500 of 122840
Processed 1600 of 122840
Processed 1700 of 122840
Processed 1800 of 122840
Processed 1900 of 122840
Processed 2000 of 122840
Processed 2100 of 122840
Processed 2200 of 122840
Processed 2300 of 122840
Processed 2400 of 122840
Processed 2500 of 122840
Processed 2600 of 122840
Processed 2700 of 122840
Processed 2800 of 122840
Processed 2900 of 122840
Processed 3000 of 122840
Processed 3100 of 122840
Processed 3200 of 122840
Processed 3300 of 122840
Processed 3400 of 122840
Processed 3500 of 122840
Processed 3600 of 122840
Processed 3700 of 122840
Processed 3800 of 122840
Processed 3900 of 122840
Processed 4000 of 122840
Processed 4100 of 122840
Processed 4200 of 122840
Processed 4300 of 122840
Processed 4400 of 122840
Processed 4500 of 122840
Processed 4600 of 122840
Processed 4700 of 122840
Processed 4800 of 122840
Processed 4900 of 122840
Processed 5000 of 122840
Processed 5100 of 122840
Processed 5200 of 122840
Processed 5300 of 122840
Processed 5400 of 122840
Processed 5500 of 122840
Processed 5600 of 122840
Processed 5700 of 122840
Processed 5800 of 122840
Processed 5900 of 122840
Processed 6000 of 122840
Processed 6100 of 122840
Processed 6200 of 122840
Processed 6300 of 122840
Processed 6400 of 122840
Processed 6500 of 122840
Processed 6600 of 122840
Processed 6700 of 122840
Processed 6800 of 122840
Processed 6900 of 122840
Processed 7000 of 122840
Processed 7100 of 122840
Processed 7200 of 122840
Processed 7300 of 122840
Processed 7400 of 122840
Processed 7500 of 122840
Processed 7600 of 122840
Processed 7700 of 122840
Processed 7800 of 122840
Processed 7900 of 122840
Processed 8000 of 122840
Processed 8100 of 122840
Processed 8200 of 122840
Processed 8300 of 122840
Processed 8400 of 122840
Processed 8500 of 122840
Processed 8600 of 122840
Processed 8700 of 122840
Processed 8800 of 122840
Processed 8900 of 122840
Processed 9000 of 122840
Processed 9100 of 122840
Processed 9200 of 122840
Processed 9300 of 122840
Processed 9400 of 122840
Processed 9500 of 122840
Processed 9600 of 122840
Processed 9700 of 122840
Processed 9800 of 122840
Processed 9900 of 122840
Processed 10000 of 122840
Processed 10100 of 122840
Processed 10200 of 122840
Processed 10300 of 122840
Processed 10400 of 122840
Processed 10500 of 122840
Processed 10600 of 122840
Processed 10700 of 122840
Processed 10800 of 122840
Processed 10900 of 122840
Processed 11000 of 122840
Processed 11100 of 122840
Processed 11200 of 122840
Processed 11300 of 122840
Processed 11400 of 122840
Processed 11500 of 122840
Processed 11600 of 122840
Processed 11700 of 122840
Processed 11800 of 122840
Processed 11900 of 122840
Processed 12000 of 122840
Processed 12100 of 122840
Processed 12200 of 122840
Processed 12300 of 122840
Processed 12400 of 122840
Processed 12500 of 122840
Processed 12600 of 122840
Processed 12700 of 122840
Processed 12800 of 122840
Processed 12900 of 122840
Processed 13000 of 122840
Processed 13100 of 122840
Processed 13200 of 122840
Processed 13300 of 122840
Processed 13400 of 122840
Processed 13500 of 122840
Processed 13600 of 122840
Processed 13700 of 122840
Processed 13800 of 122840
Processed 13900 of 122840
Processed 14000 of 122840
Processed 14100 of 122840
Processed 14200 of 122840
Processed 14300 of 122840
Processed 14400 of 122840
Processed 14500 of 122840
Processed 14600 of 122840
Processed 14700 of 122840
Processed 14800 of 122840
Processed 14900 of 122840
Processed 15000 of 122840
Processed 15100 of 122840
Processed 15200 of 122840
Processed 15300 of 122840
Processed 15400 of 122840
Processed 15500 of 122840
Processed 15600 of 122840
Processed 15700 of 122840
Processed 15800 of 122840
Processed 15900 of 122840
Processed 16000 of 122840
Processed 16100 of 122840
Processed 16200 of 122840
Processed 16300 of 122840
Processed 16400 of 122840
Processed 16500 of 122840
Processed 16600 of 122840
Processed 16700 of 122840
Processed 16800 of 122840
Processed 16900 of 122840
Processed 17000 of 122840
Processed 17100 of 122840
Processed 17200 of 122840
Processed 17300 of 122840
Processed 17400 of 122840
Processed 17500 of 122840
Processed 17600 of 122840
Processed 17700 of 122840
Processed 17800 of 122840
Processed 17900 of 122840
Processed 18000 of 122840
Processed 18100 of 122840
Processed 18200 of 122840
Processed 18300 of 122840
Processed 18400 of 122840
Processed 18500 of 122840
Processed 18600 of 122840
Processed 18700 of 122840
Processed 18800 of 122840
Processed 18900 of 122840
Processed 19000 of 122840
Processed 19100 of 122840
Processed 19200 of 122840
Processed 19300 of 122840
Processed 19400 of 122840
Processed 19500 of 122840
Processed 19600 of 122840
Processed 19700 of 122840
Processed 19800 of 122840
Processed 19900 of 122840
Processed 20000 of 122840
Processed 20100 of 122840
Processed 20200 of 122840
Processed 20300 of 122840
Processed 20400 of 122840
Processed 20500 of 122840
Processed 20600 of 122840
Processed 20700 of 122840
Processed 20800 of 122840
Processed 20900 of 122840
Processed 21000 of 122840
Processed 21100 of 122840
Processed 21200 of 122840
Processed 21300 of 122840
Processed 21400 of 122840
Processed 21500 of 122840
Processed 21600 of 122840
Processed 21700 of 122840
Processed 21800 of 122840
Processed 21900 of 122840
Processed 22000 of 122840
Processed 22100 of 122840
Processed 22200 of 122840
Processed 22300 of 122840
Processed 22400 of 122840
Processed 22500 of 122840
Processed 22600 of 122840
Processed 22700 of 122840
Processed 22800 of 122840
Processed 22900 of 122840
Processed 23000 of 122840
Processed 23100 of 122840
Processed 23200 of 122840
Processed 23300 of 122840
Processed 23400 of 122840
Processed 23500 of 122840
Processed 23600 of 122840
Processed 23700 of 122840
Processed 23800 of 122840
Processed 23900 of 122840
Processed 24000 of 122840
Processed 24100 of 122840
Processed 24200 of 122840
Processed 24300 of 122840
Processed 24400 of 122840
Processed 24500 of 122840
Processed 24600 of 122840
Processed 24700 of 122840
Processed 24800 of 122840
Processed 24900 of 122840
Processed 25000 of 122840
Processed 25100 of 122840
Processed 25200 of 122840
Processed 25300 of 122840
Processed 25400 of 122840
Processed 25500 of 122840
Processed 25600 of 122840
Processed 25700 of 122840
Processed 25800 of 122840
Processed 25900 of 122840
Processed 26000 of 122840
Processed 26100 of 122840
Processed 26200 of 122840
Processed 26300 of 122840
Processed 26400 of 122840
Processed 26500 of 122840
Processed 26600 of 122840
Processed 26700 of 122840
Processed 26800 of 122840
Processed 26900 of 122840
Processed 27000 of 122840
Processed 27100 of 122840
Processed 27200 of 122840
Processed 27300 of 122840
Processed 27400 of 122840
Processed 27500 of 122840
Processed 27600 of 122840
Processed 27700 of 122840
Processed 27800 of 122840
Processed 27900 of 122840
Processed 28000 of 122840
Processed 28100 of 122840
Processed 28200 of 122840
Processed 28300 of 122840
Processed 28400 of 122840
Processed 28500 of 122840
Processed 28600 of 122840
Processed 28700 of 122840
Processed 28800 of 122840
Processed 28900 of 122840
Processed 29000 of 122840
Processed 29100 of 122840
Processed 29200 of 122840
Processed 29300 of 122840
Processed 29400 of 122840
Processed 29500 of 122840
Processed 29600 of 122840
Processed 29700 of 122840
Processed 29800 of 122840
Processed 29900 of 122840
Processed 30000 of 122840
Processed 30100 of 122840
Processed 30200 of 122840
Processed 30300 of 122840
Processed 30400 of 122840
Processed 30500 of 122840
Processed 30600 of 122840
Processed 30700 of 122840
Processed 30800 of 122840
Processed 30900 of 122840
Processed 31000 of 122840
Processed 31100 of 122840
Processed 31200 of 122840
Processed 31300 of 122840
Processed 31400 of 122840
Processed 31500 of 122840
Processed 31600 of 122840
Processed 31700 of 122840
Processed 31800 of 122840
Processed 31900 of 122840
Processed 32000 of 122840
Processed 32100 of 122840
Processed 32200 of 122840
Processed 32300 of 122840
Processed 32400 of 122840
Processed 32500 of 122840
Processed 32600 of 122840
Processed 32700 of 122840
Processed 32800 of 122840
Processed 32900 of 122840
Processed 33000 of 122840
Processed 33100 of 122840
Processed 33200 of 122840
Processed 33300 of 122840
Processed 33400 of 122840
Processed 33500 of 122840
Processed 33600 of 122840
Processed 33700 of 122840
Processed 33800 of 122840
Processed 33900 of 122840
Processed 34000 of 122840
Processed 34100 of 122840
Processed 34200 of 122840
Processed 34300 of 122840
Processed 34400 of 122840
Processed 34500 of 122840
Processed 34600 of 122840
Processed 34700 of 122840
Processed 34800 of 122840
Processed 34900 of 122840
Processed 35000 of 122840
Processed 35100 of 122840
Processed 35200 of 122840
Processed 35300 of 122840
Processed 35400 of 122840
Processed 35500 of 122840
Processed 35600 of 122840
Processed 35700 of 122840
Processed 35800 of 122840
Processed 35900 of 122840
Processed 36000 of 122840
Processed 36100 of 122840
Processed 36200 of 122840
Processed 36300 of 122840
Processed 36400 of 122840
Processed 36500 of 122840
Processed 36600 of 122840
Processed 36700 of 122840
Processed 36800 of 122840
Processed 36900 of 122840
Processed 37000 of 122840
Processed 37100 of 122840
Processed 37200 of 122840
Processed 37300 of 122840
Processed 37400 of 122840
Processed 37500 of 122840
Processed 37600 of 122840
Processed 37700 of 122840
Processed 37800 of 122840
Processed 37900 of 122840
Processed 38000 of 122840
Processed 38100 of 122840
Processed 38200 of 122840
Processed 38300 of 122840
Processed 38400 of 122840
Processed 38500 of 122840
Processed 38600 of 122840
Processed 38700 of 122840
Processed 38800 of 122840
Processed 38900 of 122840
Processed 39000 of 122840
Processed 39100 of 122840
Processed 39200 of 122840
Processed 39300 of 122840
Processed 39400 of 122840
Processed 39500 of 122840
Processed 39600 of 122840
Processed 39700 of 122840
Processed 39800 of 122840
Processed 39900 of 122840
Processed 40000 of 122840
Processed 40100 of 122840
Processed 40200 of 122840
Processed 40300 of 122840
Processed 40400 of 122840
Processed 40500 of 122840
Processed 40600 of 122840
Processed 40700 of 122840
Processed 40800 of 122840
Processed 40900 of 122840
Processed 41000 of 122840
Processed 41100 of 122840
Processed 41200 of 122840
Processed 41300 of 122840
Processed 41400 of 122840
Processed 41500 of 122840
Processed 41600 of 122840
Processed 41700 of 122840
Processed 41800 of 122840
Processed 41900 of 122840
Processed 42000 of 122840
Processed 42100 of 122840
Processed 42200 of 122840
Processed 42300 of 122840
Processed 42400 of 122840
Processed 42500 of 122840
Processed 42600 of 122840
Processed 42700 of 122840
Processed 42800 of 122840
Processed 42900 of 122840
Processed 43000 of 122840
Processed 43100 of 122840
Processed 43200 of 122840
Processed 43300 of 122840
Processed 43400 of 122840
Processed 43500 of 122840
Processed 43600 of 122840
Processed 43700 of 122840
Processed 43800 of 122840
Processed 43900 of 122840
Processed 44000 of 122840
Processed 44100 of 122840
Processed 44200 of 122840
Processed 44300 of 122840
Processed 44400 of 122840
Processed 44500 of 122840
Processed 44600 of 122840
Processed 44700 of 122840
Processed 44800 of 122840
Processed 44900 of 122840
Processed 45000 of 122840
Processed 45100 of 122840
Processed 45200 of 122840
Processed 45300 of 122840
Processed 45400 of 122840
Processed 45500 of 122840
Processed 45600 of 122840
Processed 45700 of 122840
Processed 45800 of 122840
Processed 45900 of 122840
Processed 46000 of 122840
Processed 46100 of 122840
Processed 46200 of 122840
Processed 46300 of 122840
Processed 46400 of 122840
Processed 46500 of 122840
Processed 46600 of 122840
Processed 46700 of 122840
Processed 46800 of 122840
Processed 46900 of 122840
Processed 47000 of 122840
Processed 47100 of 122840
Processed 47200 of 122840
Processed 47300 of 122840
Processed 47400 of 122840
Processed 47500 of 122840
Processed 47600 of 122840
Processed 47700 of 122840
Processed 47800 of 122840
Processed 47900 of 122840
Processed 48000 of 122840
Processed 48100 of 122840
Processed 48200 of 122840
Processed 48300 of 122840
Processed 48400 of 122840
Processed 48500 of 122840
Processed 48600 of 122840
Processed 48700 of 122840
Processed 48800 of 122840
Processed 48900 of 122840
Processed 49000 of 122840
Processed 49100 of 122840
Processed 49200 of 122840
Processed 49300 of 122840
Processed 49400 of 122840
Processed 49500 of 122840
Processed 49600 of 122840
Processed 49700 of 122840
Processed 49800 of 122840
Processed 49900 of 122840
Processed 50000 of 122840
Processed 50100 of 122840
Processed 50200 of 122840
Processed 50300 of 122840
Processed 50400 of 122840
Processed 50500 of 122840
Processed 50600 of 122840
Processed 50700 of 122840
Processed 50800 of 122840
Processed 50900 of 122840
Processed 51000 of 122840
Processed 51100 of 122840
Processed 51200 of 122840
Processed 51300 of 122840
Processed 51400 of 122840
Processed 51500 of 122840
Processed 51600 of 122840
Processed 51700 of 122840
Processed 51800 of 122840
Processed 51900 of 122840
Processed 52000 of 122840
Processed 52100 of 122840
Processed 52200 of 122840
Processed 52300 of 122840
Processed 52400 of 122840
Processed 52500 of 122840
Processed 52600 of 122840
Processed 52700 of 122840
Processed 52800 of 122840
Processed 52900 of 122840
Processed 53000 of 122840
Processed 53100 of 122840
Processed 53200 of 122840
Processed 53300 of 122840
Processed 53400 of 122840
Processed 53500 of 122840
Processed 53600 of 122840
Processed 53700 of 122840
Processed 53800 of 122840
Processed 53900 of 122840
Processed 54000 of 122840
Processed 54100 of 122840
Processed 54200 of 122840
Processed 54300 of 122840
Processed 54400 of 122840
Processed 54500 of 122840
Processed 54600 of 122840
Processed 54700 of 122840
Processed 54800 of 122840
Processed 54900 of 122840
Processed 55000 of 122840
Processed 55100 of 122840
Processed 55200 of 122840
Processed 55300 of 122840
Processed 55400 of 122840
Processed 55500 of 122840
Processed 55600 of 122840
Processed 55700 of 122840
Processed 55800 of 122840
Processed 55900 of 122840
Processed 56000 of 122840
Processed 56100 of 122840
Processed 56200 of 122840
Processed 56300 of 122840
Processed 56400 of 122840
Processed 56500 of 122840
Processed 56600 of 122840
Processed 56700 of 122840
Processed 56800 of 122840
Processed 56900 of 122840
Processed 57000 of 122840
Processed 57100 of 122840
Processed 57200 of 122840
Processed 57300 of 122840
Processed 57400 of 122840
Processed 57500 of 122840
Processed 57600 of 122840
Processed 57700 of 122840
Processed 57800 of 122840
Processed 57900 of 122840
Processed 58000 of 122840
Processed 58100 of 122840
Processed 58200 of 122840
Processed 58300 of 122840
Processed 58400 of 122840
Processed 58500 of 122840
Processed 58600 of 122840
Processed 58700 of 122840
Processed 58800 of 122840
Processed 58900 of 122840
Processed 59000 of 122840
Processed 59100 of 122840
Processed 59200 of 122840
Processed 59300 of 122840
Processed 59400 of 122840
Processed 59500 of 122840
Processed 59600 of 122840
Processed 59700 of 122840
Processed 59800 of 122840
Processed 59900 of 122840
Processed 60000 of 122840
Processed 60100 of 122840
Processed 60200 of 122840
Processed 60300 of 122840
Processed 60400 of 122840
Processed 60500 of 122840
Processed 60600 of 122840
Processed 60700 of 122840
Processed 60800 of 122840
Processed 60900 of 122840
Processed 61000 of 122840
Processed 61100 of 122840
Processed 61200 of 122840
Processed 61300 of 122840
Processed 61400 of 122840
Processed 61500 of 122840
Processed 61600 of 122840
Processed 61700 of 122840
Processed 61800 of 122840
Processed 61900 of 122840
Processed 62000 of 122840
Processed 62100 of 122840
Processed 62200 of 122840
Processed 62300 of 122840
Processed 62400 of 122840
Processed 62500 of 122840
Processed 62600 of 122840
Processed 62700 of 122840
Processed 62800 of 122840
Processed 62900 of 122840
Processed 63000 of 122840
Processed 63100 of 122840
Processed 63200 of 122840
Processed 63300 of 122840
Processed 63400 of 122840
Processed 63500 of 122840
Processed 63600 of 122840
Processed 63700 of 122840
Processed 63800 of 122840
Processed 63900 of 122840
Processed 64000 of 122840
Processed 64100 of 122840
Processed 64200 of 122840
Processed 64300 of 122840
Processed 64400 of 122840
Processed 64500 of 122840
Processed 64600 of 122840
Processed 64700 of 122840
Processed 64800 of 122840
Processed 64900 of 122840
Processed 65000 of 122840
Processed 65100 of 122840
Processed 65200 of 122840
Processed 65300 of 122840
Processed 65400 of 122840
Processed 65500 of 122840
Processed 65600 of 122840
Processed 65700 of 122840
Processed 65800 of 122840
Processed 65900 of 122840
Processed 66000 of 122840
Processed 66100 of 122840
Processed 66200 of 122840
Processed 66300 of 122840
Processed 66400 of 122840
Processed 66500 of 122840
Processed 66600 of 122840
Processed 66700 of 122840
Processed 66800 of 122840
Processed 66900 of 122840
Processed 67000 of 122840
Processed 67100 of 122840
Processed 67200 of 122840
Processed 67300 of 122840
Processed 67400 of 122840
Processed 67500 of 122840
Processed 67600 of 122840
Processed 67700 of 122840
Processed 67800 of 122840
Processed 67900 of 122840
Processed 68000 of 122840
Processed 68100 of 122840
Processed 68200 of 122840
Processed 68300 of 122840
Processed 68400 of 122840
Processed 68500 of 122840
Processed 68600 of 122840
Processed 68700 of 122840
Processed 68800 of 122840
Processed 68900 of 122840
Processed 69000 of 122840
Processed 69100 of 122840
Processed 69200 of 122840
Processed 69300 of 122840
Processed 69400 of 122840
Processed 69500 of 122840
Processed 69600 of 122840
Processed 69700 of 122840
Processed 69800 of 122840
Processed 69900 of 122840
Processed 70000 of 122840
Processed 70100 of 122840
Processed 70200 of 122840
Processed 70300 of 122840
Processed 70400 of 122840
Processed 70500 of 122840
Processed 70600 of 122840
Processed 70700 of 122840
Processed 70800 of 122840
Processed 70900 of 122840
Processed 71000 of 122840
Processed 71100 of 122840
Processed 71200 of 122840
Processed 71300 of 122840
Processed 71400 of 122840
Processed 71500 of 122840
Processed 71600 of 122840
Processed 71700 of 122840
Processed 71800 of 122840
Processed 71900 of 122840
Processed 72000 of 122840
Processed 72100 of 122840
Processed 72200 of 122840
Processed 72300 of 122840
Processed 72400 of 122840
Processed 72500 of 122840
Processed 72600 of 122840
Processed 72700 of 122840
Processed 72800 of 122840
Processed 72900 of 122840
Processed 73000 of 122840
Processed 73100 of 122840
Processed 73200 of 122840
Processed 73300 of 122840
Processed 73400 of 122840
Processed 73500 of 122840
Processed 73600 of 122840
Processed 73700 of 122840
Processed 73800 of 122840
Processed 73900 of 122840
Processed 74000 of 122840
Processed 74100 of 122840
Processed 74200 of 122840
Processed 74300 of 122840
Processed 74400 of 122840
Processed 74500 of 122840
Processed 74600 of 122840
Processed 74700 of 122840
Processed 74800 of 122840
Processed 74900 of 122840
Processed 75000 of 122840
Processed 75100 of 122840
Processed 75200 of 122840
Processed 75300 of 122840
Processed 75400 of 122840
Processed 75500 of 122840
Processed 75600 of 122840
Processed 75700 of 122840
Processed 75800 of 122840
Processed 75900 of 122840
Processed 76000 of 122840
Processed 76100 of 122840
Processed 76200 of 122840
Processed 76300 of 122840
Processed 76400 of 122840
Processed 76500 of 122840
Processed 76600 of 122840
Processed 76700 of 122840
Processed 76800 of 122840
Processed 76900 of 122840
Processed 77000 of 122840
Processed 77100 of 122840
Processed 77200 of 122840
Processed 77300 of 122840

### A function to run search against reviews on a prefiltered set of product IDs

In [49]:

def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )
    
    return results

In [50]:
reviews = retrieve_prefiltered_reviews_data("bad_quality", ["B09Q5TNDHY"])

In [51]:
reviews

QueryResponse(points=[ScoredPoint(id=62005, version=623, score=0.5, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=80491, version=807, score=0.33333334, payload={'preprocessed_data': "Its stopped working It's not that durable", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=43190, version=434, score=0.25, payload={'preprocessed_data': "Doesn't work step tracker to sensitive It's nice, decent features good screen... but step accuracy is way off . Did the dishes and said I walked 100 steps. Also walked 100 steps in my sleep", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=105619, version=1059, score=0.2, payload={'preprocessed_data': "Didn't work I don't know if this product was defective or if it's a poor design or whatever. I'll be sending it back right away. I got it fully charged set up ,<br />went swimming, it worked during the swimming. But afterwards it cease to function and begin to act strangely vibrating almost continually.", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=47673, version=479, score=0.16666667, payload={'preprocessed_data': 'Not worth the money Watch stopped working after four months.', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None)])

In [52]:
reviews.points

[ScoredPoint(id=62005, version=623, score=0.5, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=80491, version=807, score=0.33333334, payload={'preprocessed_data': "Its stopped working It's not that durable", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=43190, version=434, score=0.25, payload={'preprocessed_data': "Doesn't work step tracker to sensitive It's nice, decent features good screen... but step accuracy is way off . Did the dishes and said I walked 100 steps. Also walked 100 steps in my sleep", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=105619, version=1059, score=0.2, payload={'preprocessed_data': "Didn't work I don't know if this product was defective or if it's a poor design or whatever. I'll be sending it back right away. I got it fully charged set up ,<br />went swimming, it worked during the swimming. But afterwards it cease to function and begin to act strangely vibrating almost continually.", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=47673, version=479, score=0.16666667, payload={'preprocessed_data': 'Not worth the money Watch stopped working after four months.', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None)]

In [53]:
reviews = retrieve_prefiltered_reviews_data("bad_quality", ["B09Q5TNDHY", "B0B4NJ8NKN" ])

In [54]:
reviews.points

[ScoredPoint(id=51290, version=515, score=0.5, payload={'preprocessed_data': 'Buena Buena', 'parent_asin': 'B0B4NJ8NKN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=71239, version=715, score=0.33333334, payload={'preprocessed_data': 'Low quality piece of trash Adapters broke within 2 weeks of usage. I wouldn’t recommend these.', 'parent_asin': 'B0B4NJ8NKN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62005, version=623, score=0.25, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=99289, version=995, score=0.2, payload={'preprocessed_data': 'Super cheap build and buzz when in use Super cheap build quality and buzz sound while using', 'parent_asin': 'B0B4NJ8NKN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=115417, version=1157, score=0.16666667, payload={'preprocessed_data': 'Defective product. The charger side does not charge. Unfortunately, I did not use them within the return window time period. Don’t waste your money', 'parent_asin': 'B0B4NJ8NKN'}, vector=None, shard_key=None, order_value=None)]

### Define the reviews retrieval tool

In [55]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )

    return response.data[0].embedding

def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    qdrant_client = QdrantClient(url="http://localhost:6333")

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_data"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
    }
    
def process_reviews_context(context):

    formatted_context = ""

    for id, chunk in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, user review: {chunk}\n"

    return formatted_context

def get_formatted_reviews_context(query: str, parent_asins: list[str], top_k: int = 5) -> str:

    """Get the top k reviews matching a query for a list of prefiltered items.
    
    Args:
        query: The query to get the top k reviews for
        item_list: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retrieve, this should be at least 20 if multipple items are prefiltered
    
    Returns:
        A string of the top k context chunks with IDs prepending each chunk, each representing a review for a given inventory item for a given query.
    """

    retrieved_context = retrieve_prefiltered_reviews_data(
        query,
        parent_asins,
        top_k
    )
    formatted_context = process_reviews_context(retrieved_context)

    return formatted_context

In [56]:
result = get_formatted_reviews_context("bad quality", ["B09Q5TNDHY", "B0B4NJ8NKN"])

In [57]:
print(result)

- ID: B0B4NJ8NKN, user review: Low quality piece of trash Adapters broke within 2 weeks of usage. I wouldn’t recommend these.
- ID: B0B4NJ8NKN, user review: Buena Buena
- ID: B09Q5TNDHY, user review: Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend
- ID: B0B4NJ8NKN, user review: Defective product. The charger side does not charge. Unfortunately, I did not use them within the return window time period. Don’t waste your money
- ID: B0B4NJ8NKN, user review: Quality product Very nice quality for price, would buy again